### ISSUE TITLE
Update for spring-native and disable automatic dependency

### ISSUE THREAD

**Issue by sdeleuze** [paketo-buildpacks/spring-boot-native-image#41]
As discussed in https://github.com/spring-projects-experimental/spring-native/issues/399, please remove automatic provisioning of `spring-graalvm-native` dependency. Notice the artifact name has been renamed from `spring-graalvm-native` to `spring-native` (same groupId).

Given this new behavior, my proposal would be to enable this buildpack when `spring-native` dependency is detected, and allow to disable it by setting `$BP_BOOT_NATIVE_IMAGE` to `false`.

For reasonable backward compatibility, please continue to detect `spring-graalvm-native` in addition to `spring-native` for now in order to not break 0.8.x users.

**Comment by ekcasey** [comment]
@sdeleuze that all sounds reasonable to me. I will make the requested changes.

**Comment by sdeleuze** [comment]
Please ping me when you need my test and feedback.

**Comment by ekcasey** [comment]
@sdeleuze I have run into a bit of an issue. The plan works well when a JAR is provided to a build but, when building from source, we do not know if the `spring-graalvm-native` or `spring-native` dependencies are present during detection. This creates a few problems:

1. We can't use the presence of `spring-graalvm-native` or  `spring-native` as the conditional to enable the buildpack.
2. In the future, when we need to select the correct version of GraalVM based on the version of `spring-native` we will have circular dependency unless we make some substantive changes. We need a JDK to build a JAR. We need to build a JAR to find the installed version of `spring-native`. We need to know the version of `spring-native` to select the correct version of the JDK to install.

I have some (admittedly ugly) ideas for how to solve the second problem. But first...

I want to do the minimum changes necessary to fix what broke with the name change:
1. Continue requiring users or platforms to set `$BP_BOOT_NATIVE_IMAGE` to opt in
2. Fail at build time if neither `spring-native` nor `spring-graalvm-native` is found.

Let me know what you think.

**Comment by sdeleuze** [comment]
As just discussed, let's continue using `$BP_BOOT_NATIVE_IMAGE` as a trigger for now and remove the automatic dependency provisionning.
